### PR TITLE
Add API for V1

### PR DESCRIPTION
**Pull request by jcmfernandes**
I'm new to `buf` and so I'm struggling to understand how you tell `buf generate` to fetch the protobufs from the schema registry. I generated the ruby from authzed@98db62d5bd9da65bdee56af487d64963bb85cb9c. Guidance is appreciated if I'm doing it wrongly :wink: .

### CODE REVIEW

**Comment by jzelinskie** [comment]
This looks good!

A few things before being merged:
- You need to sign-off on your commit. This can be done with `git commit --amend --signoff`.
- We generate protobuf code by executing `./buf.gen.yaml`, which uses the buf ref in its [shebang](https://github.com/authzed/authzed-rb/blob/main/buf.gen.yaml#L1).  Update that to `7a18d413329a4f4fb0c4237afb640e8e` and run the file to ensure everything is correct.

**Comment by jcmfernandes** [comment]
You're welcome! Commits signed off.

Damn, I even took a look at the configuration for the github action to figure out how to change `buf.gen.yaml`, but my mind refused to understand that I could simply source the YAML file :see_no_evil:. Thanks!

**Comment by jzelinskie** [comment]
The failure is CI's guarantees that regenerating produces the exact same results.
You might have to check your local version of grpc and buf to make sure everything is good.
If you're struggling, we can just merge this and I can regenerate the code reproducibly -- let me know.

**Comment by jzelinskie** [comment]
Closing this as it's stale and obviated by #15.

**Pull request closed without merging**
